update=31.03.2017 15:53:11
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[schematic_editor]
version=1
PageLayoutDescrFile=
PlotDirectoryName=
SubpartIdSeparator=0
SubpartFirstId=65
NetFmtName=Pcbnew
SpiceForceRefPrefix=0
SpiceUseNetNumbers=0
LabSize=60
[general]
version=1
[eeschema]
version=1
LibDir=
[eeschema/libraries]
LibName1=ArduinoLearningKitStarter-rescue
LibName2=robotarna_arduino-rescue
LibName3=/home/xmrazek7/kicad/lib/kicad-library/library/Zilog
LibName4=/home/xmrazek7/kicad/lib/kicad-library/library/xilinx
LibName5=/home/xmrazek7/kicad/lib/kicad-library/library/Xicor
LibName6=/home/xmrazek7/kicad/lib/kicad-library/library/Worldsemi
LibName7=/home/xmrazek7/kicad/lib/kicad-library/library/video
LibName8=/home/xmrazek7/kicad/lib/kicad-library/library/valves
LibName9=/home/xmrazek7/kicad/lib/kicad-library/library/ttl_ieee
LibName10=/home/xmrazek7/kicad/lib/kicad-library/library/transistors
LibName11=/home/xmrazek7/kicad/lib/kicad-library/library/transf
LibName12=/home/xmrazek7/kicad/lib/kicad-library/library/texas
LibName13=/home/xmrazek7/kicad/lib/kicad-library/library/switches
LibName14=/home/xmrazek7/kicad/lib/kicad-library/library/supertex
LibName15=/home/xmrazek7/kicad/lib/kicad-library/library/stm32
LibName16=/home/xmrazek7/kicad/lib/kicad-library/library/stm8
LibName17=/home/xmrazek7/kicad/lib/kicad-library/library/siliconi
LibName18=/home/xmrazek7/kicad/lib/kicad-library/library/silabs
LibName19=/home/xmrazek7/kicad/lib/kicad-library/library/sensors
LibName20=/home/xmrazek7/kicad/lib/kicad-library/library/rfcom
LibName21=/home/xmrazek7/kicad/lib/kicad-library/library/relays
LibName22=/home/xmrazek7/kicad/lib/kicad-library/library/regul
LibName23=/home/xmrazek7/kicad/lib/kicad-library/library/references
LibName24=/home/xmrazek7/kicad/lib/kicad-library/library/pspice
LibName25=/home/xmrazek7/kicad/lib/kicad-library/library/Power_Management
LibName26=/home/xmrazek7/kicad/lib/kicad-library/library/powerint
LibName27=/home/xmrazek7/kicad/lib/kicad-library/library/power
LibName28=/home/xmrazek7/kicad/lib/kicad-library/library/philips
LibName29=/home/xmrazek7/kicad/lib/kicad-library/library/Oscillators
LibName30=/home/xmrazek7/kicad/lib/kicad-library/library/opto
LibName31=/home/xmrazek7/kicad/lib/kicad-library/library/onsemi
LibName32=/home/xmrazek7/kicad/lib/kicad-library/library/nxp_armmcu
LibName33=/home/xmrazek7/kicad/lib/kicad-library/library/nordicsemi
LibName34=/home/xmrazek7/kicad/lib/kicad-library/library/msp430
LibName35=/home/xmrazek7/kicad/lib/kicad-library/library/motorola
LibName36=/home/xmrazek7/kicad/lib/kicad-library/library/motor_drivers
LibName37=/home/xmrazek7/kicad/lib/kicad-library/library/microchip_pic32mcu
LibName38=/home/xmrazek7/kicad/lib/kicad-library/library/microchip_pic18mcu
LibName39=/home/xmrazek7/kicad/lib/kicad-library/library/microchip_pic16mcu
LibName40=/home/xmrazek7/kicad/lib/kicad-library/library/microchip_pic12mcu
LibName41=/home/xmrazek7/kicad/lib/kicad-library/library/microchip_pic10mcu
LibName42=/home/xmrazek7/kicad/lib/kicad-library/library/microchip_dspic33dsc
LibName43=/home/xmrazek7/kicad/lib/kicad-library/library/microchip
LibName44=/home/xmrazek7/kicad/lib/kicad-library/library/microcontrollers
LibName45=/home/xmrazek7/kicad/lib/kicad-library/library/memory
LibName46=/home/xmrazek7/kicad/lib/kicad-library/library/maxim
LibName47=/home/xmrazek7/kicad/lib/kicad-library/library/logo
LibName48=/home/xmrazek7/kicad/lib/kicad-library/library/linear
LibName49=/home/xmrazek7/kicad/lib/kicad-library/library/Lattice
LibName50=/home/xmrazek7/kicad/lib/kicad-library/library/ir
LibName51=/home/xmrazek7/kicad/lib/kicad-library/library/interface
LibName52=/home/xmrazek7/kicad/lib/kicad-library/library/intel
LibName53=/home/xmrazek7/kicad/lib/kicad-library/library/hc11
LibName54=/home/xmrazek7/kicad/lib/kicad-library/library/graphic
LibName55=/home/xmrazek7/kicad/lib/kicad-library/library/gennum
LibName56=/home/xmrazek7/kicad/lib/kicad-library/library/ftdi
LibName57=/home/xmrazek7/kicad/lib/kicad-library/library/ESD_Protection
LibName58=/home/xmrazek7/kicad/lib/kicad-library/library/elec-unifil
LibName59=/home/xmrazek7/kicad/lib/kicad-library/library/dsp
LibName60=/home/xmrazek7/kicad/lib/kicad-library/library/display
LibName61=/home/xmrazek7/kicad/lib/kicad-library/library/diode
LibName62=/home/xmrazek7/kicad/lib/kicad-library/library/digital-audio
LibName63=/home/xmrazek7/kicad/lib/kicad-library/library/device
LibName64=/home/xmrazek7/kicad/lib/kicad-library/library/dc-dc
LibName65=/home/xmrazek7/kicad/lib/kicad-library/library/cypress
LibName66=/home/xmrazek7/kicad/lib/kicad-library/library/contrib
LibName67=/home/xmrazek7/kicad/lib/kicad-library/library/conn
LibName68=/home/xmrazek7/kicad/lib/kicad-library/library/cmos_ieee
LibName69=/home/xmrazek7/kicad/lib/kicad-library/library/cmos4000
LibName70=/home/xmrazek7/kicad/lib/kicad-library/library/brooktre
LibName71=/home/xmrazek7/kicad/lib/kicad-library/library/bbd
LibName72=/home/xmrazek7/kicad/lib/kicad-library/library/battery_management
LibName73=/home/xmrazek7/kicad/lib/kicad-library/library/audio
LibName74=/home/xmrazek7/kicad/lib/kicad-library/library/atmel
LibName75=/home/xmrazek7/kicad/lib/kicad-library/library/analog_switches
LibName76=/home/xmrazek7/kicad/lib/kicad-library/library/analog_devices
LibName77=/home/xmrazek7/kicad/lib/kicad-library/library/Altera
LibName78=/home/xmrazek7/kicad/lib/kicad-library/library/adc-dac
LibName79=/home/xmrazek7/kicad/lib/kicad-library/library/actel
LibName80=/home/xmrazek7/kicad/lib/kicad-library/library/ac-dc
LibName81=/home/xmrazek7/kicad/lib/kicad-library/library/74xx
LibName82=/home/xmrazek7/kicad/lib/kicad-library/library/74xgxx
LibName83=/home/xmrazek7/kicad/lib/downloaded/shield_arduino
LibName84=/home/xmrazek7/kicad/yaqwsx_KiCAD_lib/symbols/yaqwsx
LibName85=C:/Program Files/KiCad/share/kicad/library/74xgxx
LibName86=C:/Program Files/KiCad/share/kicad/library/74xx
LibName87=C:/Program Files/KiCad/share/kicad/library/ac-dc
LibName88=C:/Program Files/KiCad/share/kicad/library/actel
LibName89=C:/Program Files/KiCad/share/kicad/library/adc-dac
LibName90=C:/Program Files/KiCad/share/kicad/library/Altera
LibName91=C:/Program Files/KiCad/share/kicad/library/analog_devices
LibName92=C:/Program Files/KiCad/share/kicad/library/analog_switches
LibName93=C:/Program Files/KiCad/share/kicad/library/atmel
LibName94=C:/Program Files/KiCad/share/kicad/library/audio
LibName95=C:/Program Files/KiCad/share/kicad/library/battery_management
LibName96=C:/Program Files/KiCad/share/kicad/library/bbd
LibName97=C:/Program Files/KiCad/share/kicad/library/brooktre
LibName98=C:/Program Files/KiCad/share/kicad/library/cmos_ieee
LibName99=C:/Program Files/KiCad/share/kicad/library/cmos4000
LibName100=C:/Program Files/KiCad/share/kicad/library/conn
LibName101=C:/Program Files/KiCad/share/kicad/library/contrib
LibName102=C:/Program Files/KiCad/share/kicad/library/cypress
LibName103=C:/Program Files/KiCad/share/kicad/library/dc-dc
LibName104=C:/Program Files/KiCad/share/kicad/library/device
LibName105=C:/Program Files/KiCad/share/kicad/library/digital-audio
LibName106=C:/Program Files/KiCad/share/kicad/library/diode
LibName107=C:/Program Files/KiCad/share/kicad/library/display
LibName108=C:/Program Files/KiCad/share/kicad/library/dsp
LibName109=C:/Program Files/KiCad/share/kicad/library/elec-unifil
LibName110=C:/Program Files/KiCad/share/kicad/library/ESD_Protection
LibName111=C:/Program Files/KiCad/share/kicad/library/ftdi
LibName112=C:/Program Files/KiCad/share/kicad/library/gennum
LibName113=C:/Program Files/KiCad/share/kicad/library/graphic
LibName114=C:/Program Files/KiCad/share/kicad/library/hc11
LibName115=C:/Program Files/KiCad/share/kicad/library/intel
LibName116=C:/Program Files/KiCad/share/kicad/library/interface
LibName117=C:/Program Files/KiCad/share/kicad/library/ir
LibName118=C:/Program Files/KiCad/share/kicad/library/Lattice
LibName119=C:/Program Files/KiCad/share/kicad/library/linear
LibName120=C:/Program Files/KiCad/share/kicad/library/logo
LibName121=C:/Program Files/KiCad/share/kicad/library/maxim
LibName122=C:/Program Files/KiCad/share/kicad/library/memory
LibName123=C:/Program Files/KiCad/share/kicad/library/microcontrollers
LibName124=C:/Program Files/KiCad/share/kicad/library/microchip
LibName125=C:/Program Files/KiCad/share/kicad/library/microchip_dspic33dsc
LibName126=C:/Program Files/KiCad/share/kicad/library/microchip_pic10mcu
LibName127=C:/Program Files/KiCad/share/kicad/library/microchip_pic12mcu
LibName128=C:/Program Files/KiCad/share/kicad/library/microchip_pic16mcu
LibName129=C:/Program Files/KiCad/share/kicad/library/microchip_pic18mcu
LibName130=C:/Program Files/KiCad/share/kicad/library/microchip_pic32mcu
LibName131=C:/Program Files/KiCad/share/kicad/library/motor_drivers
LibName132=C:/Program Files/KiCad/share/kicad/library/motorola
LibName133=C:/Program Files/KiCad/share/kicad/library/msp430
LibName134=C:/Program Files/KiCad/share/kicad/library/nordicsemi
LibName135=C:/Program Files/KiCad/share/kicad/library/nxp_armmcu
LibName136=C:/Program Files/KiCad/share/kicad/library/onsemi
LibName137=C:/Program Files/KiCad/share/kicad/library/opto
LibName138=C:/Program Files/KiCad/share/kicad/library/Oscillators
LibName139=C:/Program Files/KiCad/share/kicad/library/philips
LibName140=C:/Program Files/KiCad/share/kicad/library/power
LibName141=C:/Program Files/KiCad/share/kicad/library/Power_Management
LibName142=C:/Program Files/KiCad/share/kicad/library/powerint
LibName143=C:/Program Files/KiCad/share/kicad/library/pspice
LibName144=C:/Program Files/KiCad/share/kicad/library/references
LibName145=C:/Program Files/KiCad/share/kicad/library/regul
LibName146=C:/Program Files/KiCad/share/kicad/library/relays
LibName147=C:/Program Files/KiCad/share/kicad/library/rfcom
LibName148=C:/Program Files/KiCad/share/kicad/library/sensors
LibName149=C:/Program Files/KiCad/share/kicad/library/silabs
LibName150=C:/Program Files/KiCad/share/kicad/library/siliconi
LibName151=C:/Program Files/KiCad/share/kicad/library/stm8
LibName152=C:/Program Files/KiCad/share/kicad/library/stm32
LibName153=C:/Program Files/KiCad/share/kicad/library/supertex
LibName154=C:/Program Files/KiCad/share/kicad/library/switches
LibName155=C:/Program Files/KiCad/share/kicad/library/texas
LibName156=C:/Program Files/KiCad/share/kicad/library/transf
LibName157=C:/Program Files/KiCad/share/kicad/library/transistors
LibName158=C:/Program Files/KiCad/share/kicad/library/ttl_ieee
LibName159=C:/Program Files/KiCad/share/kicad/library/valves
LibName160=C:/Program Files/KiCad/share/kicad/library/video
LibName161=C:/Program Files/KiCad/share/kicad/library/Worldsemi
LibName162=C:/Program Files/KiCad/share/kicad/library/Xicor
LibName163=C:/Program Files/KiCad/share/kicad/library/xilinx
LibName164=C:/Program Files/KiCad/share/kicad/library/Zilog
