update=05.10.2016 22:07:24
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[schematic_editor]
version=1
PageLayoutDescrFile=
PlotDirectoryName=
SubpartIdSeparator=0
SubpartFirstId=65
NetFmtName=Pcbnew
SpiceForceRefPrefix=0
SpiceUseNetNumbers=0
LabSize=60
[eeschema]
version=1
LibDir=
[eeschema/libraries]
LibName1=robotarna_arduino-rescue
LibName2=/home/xmrazek7/kicad/lib/kicad-library/library/Zilog
LibName3=/home/xmrazek7/kicad/lib/kicad-library/library/xilinx
LibName4=/home/xmrazek7/kicad/lib/kicad-library/library/Xicor
LibName5=/home/xmrazek7/kicad/lib/kicad-library/library/Worldsemi
LibName6=/home/xmrazek7/kicad/lib/kicad-library/library/video
LibName7=/home/xmrazek7/kicad/lib/kicad-library/library/valves
LibName8=/home/xmrazek7/kicad/lib/kicad-library/library/ttl_ieee
LibName9=/home/xmrazek7/kicad/lib/kicad-library/library/transistors
LibName10=/home/xmrazek7/kicad/lib/kicad-library/library/transf
LibName11=/home/xmrazek7/kicad/lib/kicad-library/library/texas
LibName12=/home/xmrazek7/kicad/lib/kicad-library/library/switches
LibName13=/home/xmrazek7/kicad/lib/kicad-library/library/supertex
LibName14=/home/xmrazek7/kicad/lib/kicad-library/library/stm32
LibName15=/home/xmrazek7/kicad/lib/kicad-library/library/stm8
LibName16=/home/xmrazek7/kicad/lib/kicad-library/library/siliconi
LibName17=/home/xmrazek7/kicad/lib/kicad-library/library/silabs
LibName18=/home/xmrazek7/kicad/lib/kicad-library/library/sensors
LibName19=/home/xmrazek7/kicad/lib/kicad-library/library/rfcom
LibName20=/home/xmrazek7/kicad/lib/kicad-library/library/relays
LibName21=/home/xmrazek7/kicad/lib/kicad-library/library/regul
LibName22=/home/xmrazek7/kicad/lib/kicad-library/library/references
LibName23=/home/xmrazek7/kicad/lib/kicad-library/library/pspice
LibName24=/home/xmrazek7/kicad/lib/kicad-library/library/Power_Management
LibName25=/home/xmrazek7/kicad/lib/kicad-library/library/powerint
LibName26=/home/xmrazek7/kicad/lib/kicad-library/library/power
LibName27=/home/xmrazek7/kicad/lib/kicad-library/library/philips
LibName28=/home/xmrazek7/kicad/lib/kicad-library/library/Oscillators
LibName29=/home/xmrazek7/kicad/lib/kicad-library/library/opto
LibName30=/home/xmrazek7/kicad/lib/kicad-library/library/onsemi
LibName31=/home/xmrazek7/kicad/lib/kicad-library/library/nxp_armmcu
LibName32=/home/xmrazek7/kicad/lib/kicad-library/library/nordicsemi
LibName33=/home/xmrazek7/kicad/lib/kicad-library/library/msp430
LibName34=/home/xmrazek7/kicad/lib/kicad-library/library/motorola
LibName35=/home/xmrazek7/kicad/lib/kicad-library/library/motor_drivers
LibName36=/home/xmrazek7/kicad/lib/kicad-library/library/microchip_pic32mcu
LibName37=/home/xmrazek7/kicad/lib/kicad-library/library/microchip_pic18mcu
LibName38=/home/xmrazek7/kicad/lib/kicad-library/library/microchip_pic16mcu
LibName39=/home/xmrazek7/kicad/lib/kicad-library/library/microchip_pic12mcu
LibName40=/home/xmrazek7/kicad/lib/kicad-library/library/microchip_pic10mcu
LibName41=/home/xmrazek7/kicad/lib/kicad-library/library/microchip_dspic33dsc
LibName42=/home/xmrazek7/kicad/lib/kicad-library/library/microchip
LibName43=/home/xmrazek7/kicad/lib/kicad-library/library/microcontrollers
LibName44=/home/xmrazek7/kicad/lib/kicad-library/library/memory
LibName45=/home/xmrazek7/kicad/lib/kicad-library/library/maxim
LibName46=/home/xmrazek7/kicad/lib/kicad-library/library/logo
LibName47=/home/xmrazek7/kicad/lib/kicad-library/library/linear
LibName48=/home/xmrazek7/kicad/lib/kicad-library/library/Lattice
LibName49=/home/xmrazek7/kicad/lib/kicad-library/library/ir
LibName50=/home/xmrazek7/kicad/lib/kicad-library/library/interface
LibName51=/home/xmrazek7/kicad/lib/kicad-library/library/intel
LibName52=/home/xmrazek7/kicad/lib/kicad-library/library/hc11
LibName53=/home/xmrazek7/kicad/lib/kicad-library/library/graphic
LibName54=/home/xmrazek7/kicad/lib/kicad-library/library/gennum
LibName55=/home/xmrazek7/kicad/lib/kicad-library/library/ftdi
LibName56=/home/xmrazek7/kicad/lib/kicad-library/library/ESD_Protection
LibName57=/home/xmrazek7/kicad/lib/kicad-library/library/elec-unifil
LibName58=/home/xmrazek7/kicad/lib/kicad-library/library/dsp
LibName59=/home/xmrazek7/kicad/lib/kicad-library/library/display
LibName60=/home/xmrazek7/kicad/lib/kicad-library/library/diode
LibName61=/home/xmrazek7/kicad/lib/kicad-library/library/digital-audio
LibName62=/home/xmrazek7/kicad/lib/kicad-library/library/device
LibName63=/home/xmrazek7/kicad/lib/kicad-library/library/dc-dc
LibName64=/home/xmrazek7/kicad/lib/kicad-library/library/cypress
LibName65=/home/xmrazek7/kicad/lib/kicad-library/library/contrib
LibName66=/home/xmrazek7/kicad/lib/kicad-library/library/conn
LibName67=/home/xmrazek7/kicad/lib/kicad-library/library/cmos_ieee
LibName68=/home/xmrazek7/kicad/lib/kicad-library/library/cmos4000
LibName69=/home/xmrazek7/kicad/lib/kicad-library/library/brooktre
LibName70=/home/xmrazek7/kicad/lib/kicad-library/library/bbd
LibName71=/home/xmrazek7/kicad/lib/kicad-library/library/battery_management
LibName72=/home/xmrazek7/kicad/lib/kicad-library/library/audio
LibName73=/home/xmrazek7/kicad/lib/kicad-library/library/atmel
LibName74=/home/xmrazek7/kicad/lib/kicad-library/library/analog_switches
LibName75=/home/xmrazek7/kicad/lib/kicad-library/library/analog_devices
LibName76=/home/xmrazek7/kicad/lib/kicad-library/library/Altera
LibName77=/home/xmrazek7/kicad/lib/kicad-library/library/adc-dac
LibName78=/home/xmrazek7/kicad/lib/kicad-library/library/actel
LibName79=/home/xmrazek7/kicad/lib/kicad-library/library/ac-dc
LibName80=/home/xmrazek7/kicad/lib/kicad-library/library/74xx
LibName81=/home/xmrazek7/kicad/lib/kicad-library/library/74xgxx
LibName82=/home/xmrazek7/kicad/lib/downloaded/shield_arduino
LibName83=/home/xmrazek7/kicad/yaqwsx_KiCAD_lib/symbols/yaqwsx
LibName84=C:/Program Files/KiCad/share/kicad/library/74xgxx
LibName85=C:/Program Files/KiCad/share/kicad/library/74xx
LibName86=C:/Program Files/KiCad/share/kicad/library/ac-dc
LibName87=C:/Program Files/KiCad/share/kicad/library/actel
LibName88=C:/Program Files/KiCad/share/kicad/library/adc-dac
LibName89=C:/Program Files/KiCad/share/kicad/library/Altera
LibName90=C:/Program Files/KiCad/share/kicad/library/analog_devices
LibName91=C:/Program Files/KiCad/share/kicad/library/analog_switches
LibName92=C:/Program Files/KiCad/share/kicad/library/atmel
LibName93=C:/Program Files/KiCad/share/kicad/library/audio
LibName94=C:/Program Files/KiCad/share/kicad/library/battery_management
LibName95=C:/Program Files/KiCad/share/kicad/library/bbd
LibName96=C:/Program Files/KiCad/share/kicad/library/brooktre
LibName97=C:/Program Files/KiCad/share/kicad/library/cmos_ieee
LibName98=C:/Program Files/KiCad/share/kicad/library/cmos4000
LibName99=C:/Program Files/KiCad/share/kicad/library/conn
LibName100=C:/Program Files/KiCad/share/kicad/library/contrib
LibName101=C:/Program Files/KiCad/share/kicad/library/cypress
LibName102=C:/Program Files/KiCad/share/kicad/library/dc-dc
LibName103=C:/Program Files/KiCad/share/kicad/library/device
LibName104=C:/Program Files/KiCad/share/kicad/library/digital-audio
LibName105=C:/Program Files/KiCad/share/kicad/library/diode
LibName106=C:/Program Files/KiCad/share/kicad/library/display
LibName107=C:/Program Files/KiCad/share/kicad/library/dsp
LibName108=C:/Program Files/KiCad/share/kicad/library/elec-unifil
LibName109=C:/Program Files/KiCad/share/kicad/library/ESD_Protection
LibName110=C:/Program Files/KiCad/share/kicad/library/ftdi
LibName111=C:/Program Files/KiCad/share/kicad/library/gennum
LibName112=C:/Program Files/KiCad/share/kicad/library/graphic
LibName113=C:/Program Files/KiCad/share/kicad/library/hc11
LibName114=C:/Program Files/KiCad/share/kicad/library/intel
LibName115=C:/Program Files/KiCad/share/kicad/library/interface
LibName116=C:/Program Files/KiCad/share/kicad/library/ir
LibName117=C:/Program Files/KiCad/share/kicad/library/Lattice
LibName118=C:/Program Files/KiCad/share/kicad/library/linear
LibName119=C:/Program Files/KiCad/share/kicad/library/logo
LibName120=C:/Program Files/KiCad/share/kicad/library/maxim
LibName121=C:/Program Files/KiCad/share/kicad/library/memory
LibName122=C:/Program Files/KiCad/share/kicad/library/microcontrollers
LibName123=C:/Program Files/KiCad/share/kicad/library/microchip
LibName124=C:/Program Files/KiCad/share/kicad/library/microchip_dspic33dsc
LibName125=C:/Program Files/KiCad/share/kicad/library/microchip_pic10mcu
LibName126=C:/Program Files/KiCad/share/kicad/library/microchip_pic12mcu
LibName127=C:/Program Files/KiCad/share/kicad/library/microchip_pic16mcu
LibName128=C:/Program Files/KiCad/share/kicad/library/microchip_pic18mcu
LibName129=C:/Program Files/KiCad/share/kicad/library/microchip_pic32mcu
LibName130=C:/Program Files/KiCad/share/kicad/library/motor_drivers
LibName131=C:/Program Files/KiCad/share/kicad/library/motorola
LibName132=C:/Program Files/KiCad/share/kicad/library/msp430
LibName133=C:/Program Files/KiCad/share/kicad/library/nordicsemi
LibName134=C:/Program Files/KiCad/share/kicad/library/nxp_armmcu
LibName135=C:/Program Files/KiCad/share/kicad/library/onsemi
LibName136=C:/Program Files/KiCad/share/kicad/library/opto
LibName137=C:/Program Files/KiCad/share/kicad/library/Oscillators
LibName138=C:/Program Files/KiCad/share/kicad/library/philips
LibName139=C:/Program Files/KiCad/share/kicad/library/power
LibName140=C:/Program Files/KiCad/share/kicad/library/Power_Management
LibName141=C:/Program Files/KiCad/share/kicad/library/powerint
LibName142=C:/Program Files/KiCad/share/kicad/library/pspice
LibName143=C:/Program Files/KiCad/share/kicad/library/references
LibName144=C:/Program Files/KiCad/share/kicad/library/regul
LibName145=C:/Program Files/KiCad/share/kicad/library/relays
LibName146=C:/Program Files/KiCad/share/kicad/library/rfcom
LibName147=C:/Program Files/KiCad/share/kicad/library/sensors
LibName148=C:/Program Files/KiCad/share/kicad/library/silabs
LibName149=C:/Program Files/KiCad/share/kicad/library/siliconi
LibName150=C:/Program Files/KiCad/share/kicad/library/stm8
LibName151=C:/Program Files/KiCad/share/kicad/library/stm32
LibName152=C:/Program Files/KiCad/share/kicad/library/supertex
LibName153=C:/Program Files/KiCad/share/kicad/library/switches
LibName154=C:/Program Files/KiCad/share/kicad/library/texas
LibName155=C:/Program Files/KiCad/share/kicad/library/transf
LibName156=C:/Program Files/KiCad/share/kicad/library/transistors
LibName157=C:/Program Files/KiCad/share/kicad/library/ttl_ieee
LibName158=C:/Program Files/KiCad/share/kicad/library/valves
LibName159=C:/Program Files/KiCad/share/kicad/library/video
LibName160=C:/Program Files/KiCad/share/kicad/library/Worldsemi
LibName161=C:/Program Files/KiCad/share/kicad/library/Xicor
LibName162=C:/Program Files/KiCad/share/kicad/library/xilinx
LibName163=C:/Program Files/KiCad/share/kicad/library/Zilog
